Add /guilds endpoints
Tech-With-Tim/API pull request #32
Opened 2021-01-16 19:04 UTC by takos22

## Summary

I added `/guilds` endpoints and the models needed for it. I also updated the way tests are done and added tests that need a test database.

## Checklist

- [x] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [x] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-01-21 15:23 UTC, SylteA requested changes

2021-01-21 15:23 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +    if not all(c in data for c in GUILD_COLUMNS):
Please switch to added validators.

2021-01-21 15:23 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +            jsonify(
I'm working on standardizing the `jsonify` usage in our repository.

All usage of `jsonify` will be done like [this](https://github.com/Tech-With-Tim/API/blob/f83ce39e46fb058e33ff5c6a36671fa004363de9/utils/validators.py#L166-L169)

2021-01-21 15:23 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +    )
Instead of defining the response and adding headers, you can use [this ](https://pgjones.gitlab.io/quart/reference/response_values.html?highlight=return#combinations) syntax, it's much faster to develop like this and looks better.

2021-01-21 15:23 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +    return jsonify(
Instead of returning data that's no longer in our database, you could really just return a `204 - No Content` response.

2021-01-21 15:23 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +@bp.route("/<int:guild_id>/config", methods=["POST"])
(imo) GuildConfigs could be handled in a different view file (ex: `api/blueprints/guilds/views/configs.py`, overall cleaner this way.

2021-01-21 15:23 UTC, SylteA commented on api/models/guild.py
> +        allowed_fields = ("name", "owner_id", "icon_hash")
This should be handled in the view updating the guild. (Is handled by validator)

2021-01-21 15:23 UTC, SylteA commented on api/models/guild.py
> +        format: Literal["jpeg", "jpg", "webp", "png", "gif"] = None,
please change `format` to something else (ex: `fmt`) as format is a builtin.

2021-01-21 15:23 UTC, SylteA commented on launch.py
> +    loop = loop or LOOP
Instead of making these optional then defining them like this, why not make it required and remove this?

2021-01-21 17:39 UTC, takos22 commented on api/blueprints/guilds/views/guilds.py
> +    )
I didnt know about this, thanks

2021-01-21 20:23 UTC, takos22 commented on api/models/guild.py
> +        allowed_fields = ("name", "owner_id", "icon_hash")
It is way simpler and cleaner like this (imo)

2021-01-21 20:27 UTC, SylteA commented on api/models/guild.py
> +        allowed_fields = ("name", "owner_id", "icon_hash")
Validator will handle it anyways, no need to do it twice

2021-01-21 21:28 UTC, SylteA requested changes

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +    except ValueError as e:
This should never be raised as it's handled by validator

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +@bp.route("/<int:guild_id>/config", methods=["POST"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +@bp.route("/<int:guild_id>/config", methods=["GET"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +@bp.route("/<int:guild_id>/config", methods=["PATCH"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +@bp.route("/<int:guild_id>/config", methods=["DELETE"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +@bp.route("", methods=["POST"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +@bp.route("/<int:guild_id>", methods=["PATCH"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on api/blueprints/guilds/views/guilds.py
> +@bp.route("/<int:guild_id>", methods=["DELETE"])
remember to limit access (utils.app_only)

2021-01-21 21:28 UTC, SylteA commented on tests/test_guilds.py
> +        assert json["icon_hash"] == data.get("icon_hash", None)
instead of asserting each keypair, assert the entire dict?

2021-01-21 21:28 UTC, SylteA commented on tests/test_guilds.py
> +    assert json["error"] == "Not found"
Instead of this, do 
```python
    assert (await response.json) == {...}
```

2021-01-23 23:45 UTC, SylteA commented on api/models/guild.py
> +        )
This will work, but is bad practice.

2021-01-24 00:22 UTC, SylteA requested changes

2021-01-24 00:22 UTC, SylteA commented on api/models/guild.py
> +            )
Please add a docstring and generally clean up this code.
Just adding a couple spaces would clean it up alot.

2021-01-24 00:22 UTC, SylteA commented on api/models/guild.py
> +            return None
There are default icons even for guilds, we should return a default instead of None.

2021-01-24 00:22 UTC, SylteA commented on api/models/guild_config.py
> +class GuildConfig(Model):
Missing docstring.

2021-01-24 00:22 UTC, SylteA commented on api/models/guild_config.py
> +        SET ({", ".join(allowed_fields)}) = ($2, $3, $4, $5, $6, $7, $8, $9, $10)
formatting a query like this is not very clean.
It's preferred if you did something like: 
```sql
UPDATE guildconfigs
SET
  xp_enabled = $2,
  xp_multiplier = $3,
  ...
WHERE guild_id = $1
RETURNING *;
```

This also counts for the other update method you have made.

2021-01-24 00:22 UTC, SylteA commented on tests/test_guilds.py
> +        "/guilds/523456202403"
could of just written 0 :p

2021-01-27 20:21 UTC, takos22 commented on api/models/guild.py
> +            return None
Are you sure about that?
This is when there is an icon:
![image](https://user-images.githubusercontent.com/59511469/106048673-79ab9f80-60e5-11eb-9052-951378f2ca45.png)
This is when there isn't an icon:
![image](https://user-images.githubusercontent.com/59511469/106048771-9647d780-60e5-11eb-96c4-755fe2570191.png)

2021-01-30 16:06 UTC, SylteA requested changes

2021-01-30 16:06 UTC, SylteA commented on README.md
> +- [@takos22](https://github.com/takos22) - /guilds endpoints and markdown files
I wasnt thinking we'd add info on who made what endpoints

2021-01-30 16:06 UTC, SylteA commented on api/blueprints/guilds/views/configs.py
> +    guild = await Guild.fetch_or_404(guild_id)
Why are you fetching the guild first?
There wont be a config if there is no guild.

2021-01-30 16:06 UTC, SylteA commented on api/models/guild.py
> +    :param str icon_hash:   The guilds icon hash.
this is `Optional[str]`

2021-01-30 16:06 UTC, SylteA commented on api/models/guild.py
> +        else:
no need for else, no need for custom descriptions.

2021-01-30 21:52 UTC, SylteA approved these changes
congrats 🥇

2021-01-30 21:56 UTC, merged