Update README.md | Typos fixed
Tech-With-Tim/API pull request #35
Opened 2021-01-20 16:09 UTC by saptarshibasu15

## Summary

Some typos like, stricly(strictly), Licence(License), Initialise(Initialize)... 
we're fixed! Thanks me later.

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-01-20 18:03 UTC, takos22 requested changes
We are using British English so `licence` and `initialise` are correct.

2021-01-20 18:03 UTC, takos22 commented on README.md
> -Run the API and initialise the database:
We are using British English so `initialise` is correct.

2021-01-20 18:03 UTC, takos22 commented on README.md
> -[![Licence](https://img.shields.io/badge/licence-MIT-blue.svg)](/LICENCE)
We are using British English so `licence` is correct.

2021-01-20 18:03 UTC, takos22 commented on README.md
> -- [📜 Licence](/LICENCE)
We are using British English so `licence` is correct.

2021-01-21 05:44 UTC, saptarshibasu15 commented on README.md
> -- [📜 Licence](/LICENCE)
Got it fixed

2021-01-21 06:07 UTC, takos22 approved these changes
Ok thanks

2021-01-21 14:42 UTC, merged