Adds Permissions, Roles and Snowflake IDS
Tech-With-Tim/API pull request #42
Opened 2021-02-27 10:13 UTC by mohamed040406

## Summary

Added Permissions and Roles Models and the SQL functions for `Snowflake IDS` and checking for global permissions

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-02-27 18:49 UTC, SylteA requested changes
When you finish the requested changes
Either finish role related endpoints or push this to its own branch so someone can finish it.

2021-02-27 18:49 UTC, SylteA commented on api/models/permission.py
> +                "name": "Manage Global Roles",
No need for "global" keyword

2021-02-27 18:49 UTC, SylteA commented on api/models/permission.py
> +                " and will also bypass all channel specific permissions or restrictions.",
"channel specific permissions"?..

2021-02-27 18:49 UTC, SylteA commented on api/models/permission.py
> +                "name": "Create Timathon",
Dont make permissions timathon specific, you also have weekly challenges.

2021-04-15 15:14 UTC, SylteA commented
Needs tests & documentation to be finished before merging.

2021-06-11 20:50 UTC, mohamed040406 commented
nvm

2021-06-11 20:50 UTC, closed without merging