Sarzz
Tech-With-Tim/API pull request #45
Opened 2021-04-10 10:16 UTC by sarzz2

## Summary

Added new endpoint to create weekly challenges

## Checklist

- [x] If endpoints were changed then they have been documented and tested.
    - [x] I have updated the docmentation to reflect the changes.
    - [x] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-10 13:48 UTC, mohamed040406 requested changes

2021-04-10 13:48 UTC, mohamed040406 commented on api/app.py
> +weekly_challenges.setup(app=app, url_prefix="/wkc")
make better endpoint name please... thx

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +    created_by = Column(types.String())
this should be a relation with the `id` column from users model

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +           """
the `id` should be `create_snowflake()`

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +        )
can you update only fields that was passed as args? not really required ~~or is it required? ask @SylteA~~

2021-04-10 13:48 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +@bp.route("/<int:weekly_challenge_id>", methods=["DELETE"])
auth and perms decorators missing?

2021-04-10 13:48 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +@bp.route("/<int:weekly_challenge_id>", methods=["PATCH"])
auth and perms decorators missing?

2021-04-10 13:48 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +)
auth and perms decorators missing?

also `id` is created on backend

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +        """Returns """
Returns... ~~that was a useless comment tbh~~

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +        return self
why return object on delete?

2021-04-10 13:48 UTC, mohamed040406 commented on api/models/weekly_challenge.py
> +        query = "SELECT * FROM challenges WHERE id = $1"
When fetching make sure to cast the `id` and `created_by` to strings

2021-04-10 13:48 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +    await weekly_challenge.delete()
why are you fetching before deleting?

2021-04-10 13:48 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +        {"Location": f"/{challenge.id}"},
this is not the correct location

2021-04-10 13:50 UTC, mohamed040406 commented on api/blueprints/weekly_challenges/views/weekly_challenges.py
> +    created_by: str,
`created by` is the user who made the request so you should get that from `request.user.id`

2021-04-11 07:58 UTC, mohamed040406 requested changes

2021-04-11 07:58 UTC, mohamed040406 commented on api/models/weekly.py
> +        raise exceptions.NotFound(http_status)
sylte said no fetch_or_404? 👀

2021-04-11 07:58 UTC, mohamed040406 commented on api/blueprints/challenges/views/weeklyc.py
> +    return jsonify("Challenge Deleted", 204)
no need to fetch before deleting 👀

2021-04-11 07:58 UTC, mohamed040406 commented on api/blueprints/challenges/views/weeklyc.py
> +    await challenge.update(**data)
no need to fetch before updating? 👀

2021-04-11 07:58 UTC, mohamed040406 commented on api/blueprints/challenges/views/weeklyc.py
> +        )
what is this? 👀

2021-04-11 08:04 UTC, sarzz2 commented on api/blueprints/challenges/views/weeklyc.py
> +        )
Return statement if challenge select exists?

2021-04-11 08:48 UTC, mohamed040406 commented on api/blueprints/challenges/views/weeklyc.py
> +        )
when will this happen?

2021-04-15 15:21 UTC, SylteA commented on api/blueprints/challenges/views/__init__.py
> +from . import weeklyc  # noqa F401
Rename imported file to `weekly.py`

2021-04-15 15:24 UTC, SylteA commented on api/blueprints/challenges/views/weeklyc.py
> +async def post_challenge(
- There is no checking of the challenge difficulty.
- You are not handling possible errors from Challenge.create 
  OR checking the arguments which could result in errors beforehand.

2021-04-15 15:25 UTC, SylteA commented on api/blueprints/challenges/views/weeklyc.py
> +async def update_challenge(weekly_challenge_id: int, **data):
You're not even expecting them to authenticate to update a challenge...
All logic in this endpoint is also written on a classmethod instead of the endpoint (bad practice).

2021-04-15 15:26 UTC, SylteA commented on api/models/__init__.py
> +from .weekly import Challenge
Please fix the ordering of your imports

2021-04-15 15:26 UTC, SylteA commented on api/models/weekly.py
> +        created_by: str,
`created_by` should be `Union[str, int]` and converted to int in fetchrow()

2021-04-15 15:27 UTC, SylteA commented on api/models/weekly.py
> +    async def update(cls, weekly_challenge_id: int = None, **data):
No validation on the data, you're just inputting it no matter what

2021-04-15 15:29 UTC, SylteA commented on tests/test_weekly_challenges.py
> +        "description": str(challenge.description),
What other type could challenge.description be that would require you to convert it to a string?

2021-06-11 05:10 UTC, closed without merging