FastAPI rewrite initial commit
Tech-With-Tim/API pull request #47
Opened 2021-06-11 21:58 UTC by takos22

## Summary

Basic FastAPI project structure

Co-Authored-By: sarzz <45039724+sarzz2@users.noreply.github.com>

## Checklist

- [x] If endpoints were changed then they have been documented and tested.
    - [x] I have updated the docmentation to reflect the changes.
    - [x] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [x] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-12 23:35 UTC, SylteA requested changes

2021-06-12 23:35 UTC, SylteA commented on .pre-commit-config.yaml
> +        entry: black --check . --line-length 80
Please use line length 120

2021-06-12 23:35 UTC, SylteA commented on Pipfile
> +requests = "*"
- Move this to dev-packages.
- No need to specify extras for uvicorn?..
- Add whichever other dependencies you'll need now, will save you alot of time in installing new ones.

2021-06-12 23:35 UTC, SylteA commented on Dockerfile
> -CMD python launch.py runserver --host 0.0.0.0 --port 5000 --initdb --debug
Why are you removing docker files completely?
I have improved dockerfile versions you can have later

2021-06-12 23:35 UTC, SylteA commented on api/__init__.py
> +from .main import app
I like how you add a pre-commit config but don't run it before comitting.
(missing newline at the end of file)

2021-06-12 23:35 UTC, SylteA commented on api/main.py
> +from fastapi.middleware.gzip import GZipMiddleware
I don't really think we need GZip compliance

2021-06-12 23:35 UTC, SylteA commented on tests/test_index.py
> +client = TestClient(app)
Use fixtures

2021-06-12 23:35 UTC, SylteA commented on tests/test_index.py
> +def test_read_main():
Try to avoid multiple assertions in the same test, something I've learned lately.
Also use more accucate test names. (`test_read_main` is really broad.)
Should also use the file tree more for tests.

2021-06-12 23:35 UTC, SylteA commented on setup.cfg
> +    __init__.py: F401
I don't really like this solution as it could block actual issues..

2021-06-13 03:18 UTC, mohamed040406 commented on Pipfile
> +requests = "*"
- why move to dev-packages?
- Maybe because of [this](https://www.uvicorn.org/#quickstart)? :eyes:

2021-06-13 03:18 UTC, mohamed040406 commented
why did you delete the cli?...

2021-06-13 19:44 UTC, SylteA commented on Pipfile
> +requests = "*"
requests is only required for tests, therefore it should be a dev dependency.

2021-06-13 19:44 UTC, SylteA commented
> why did you delete the cli?...

Yeah alot of removed content was unnecessary

2021-06-22 09:10 UTC, closed without merging