Yet another fastapi rewrite PR
Tech-With-Tim/API pull request #49
Opened 2021-06-19 17:42 UTC by mohamed040406

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [x] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-19 18:52 UTC, SylteA requested changes
Did it all from my phone so might have missed something.

2021-06-19 18:52 UTC, SylteA commented on Dockerfile
> +COPY Pipfile.lock Pipfile.lock
This can be simplified to a single line.

```Dockerfile
COPY Pipfile Pipfile.lock ./
```

2021-06-19 18:52 UTC, SylteA commented on Dockerfile
> +CMD python launch.py runserver --initdb --verbose
Please include --debug as this is the development Dockerfile.

(For production builds add a `prod.Dockerfile`)

2021-06-19 18:52 UTC, SylteA commented on Pipfile
> +test = "pytest"
Please use `python -m pytest`.
This will run from root directory and solve any issues with working directory

2021-06-19 18:52 UTC, SylteA commented on README.md
> +- `SECRET_KEY` is the key used for the JWT token encoding.
used for ~~the~~ JWT token encoding.

2021-06-19 18:52 UTC, SylteA commented on api/app.py
> +    return {"status": "ok"}
Please remove this.

2021-06-19 18:52 UTC, SylteA commented on api/models/__init__.py
> +models_ordered = []
Please include typing.

2021-06-19 18:52 UTC, SylteA commented on tests/test_index.py
> +    assert response.json() == {"status": "ok"}
No need for this endpoint nor test.

2021-06-19 18:52 UTC, SylteA commented on tests/conftest.py
> +from api import app as fastapi_app
Move this inside the fixture definition.

2021-06-19 18:52 UTC, SylteA commented on launch.py
>      )
Can we find a better way to validate env?
How about just defaulting to running with Docker?
What about a `config.py` file where we load all env values and dispatch a warning if they are not found?

2021-06-19 18:52 UTC, SylteA commented on launch.py
> +    config = Config("api.app:app", reload=reload, host=host, port=port, debug=debug)
My guess is you haven't actually tested running this? because iirc it'll error as you have different event loops between postDB and fastAPI.
If you remind me later I'll give you my solution to this.

2021-06-19 18:52 UTC, SylteA commented on api/app.py
> +app.router.default_response_class = JSONResponse
If we could also prepend all routes with `/v1` so we can easier migrate APIs later.

```python
app.router.prefix = "v1"
```
Should be something like that ^

2021-06-19 18:58 UTC, mohamed040406 commented on launch.py
> +    config = Config("api.app:app", reload=reload, host=host, port=port, debug=debug)
actually i did, and it worked fine. 🤷‍♂️

2021-06-19 18:59 UTC, mohamed040406 commented on tests/test_index.py
> +    assert response.json() == {"status": "ok"}
ok will remove them.

2021-06-19 19:03 UTC, mohamed040406 commented on Dockerfile
> +CMD python launch.py runserver --initdb --verbose
should i also include reload?

2021-06-19 19:07 UTC, mohamed040406 commented on api/app.py
> +app.router.default_response_class = JSONResponse
adding `app.router.prefix = "v1"` will set the prefix to **all** the routes so we will have to make a new router for it. We can do that once we start working on routes.

2021-06-19 19:09 UTC, SylteA commented on Dockerfile
> +CMD python launch.py runserver --initdb --verbose
no lol not with docker 😅

2021-06-19 19:10 UTC, mohamed040406 commented on Dockerfile
> +CMD python launch.py runserver --initdb --verbose
ok :ugundu:

2021-06-19 19:10 UTC, SylteA commented on launch.py
> +    config = Config("api.app:app", reload=reload, host=host, port=port, debug=debug)
Ok

2021-06-19 19:11 UTC, SylteA commented on api/app.py
> +app.router.default_response_class = JSONResponse
Then create another router `v1router`..

2021-06-19 20:41 UTC, takos22 requested changes
You forgot to rename a cli command but lgtm

2021-06-19 20:41 UTC, takos22 commented on api/app.py
>      def __init__(self, *args, **kwargs):
Just remove this 😂

2021-06-19 20:41 UTC, takos22 commented on README.md
>  - [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio) - Test framework (asynchronous version of [pytest](https://docs.pytest.org/en/stable/))
Shouldn't we add pytest here, because pytest-asyncio is just a plugin for async tests, the test framework is pytest

2021-06-19 20:41 UTC, takos22 commented on launch.py
> +@cli.command()
You forgot `name="dropdb"`

2021-06-20 13:25 UTC, SylteA requested changes

2021-06-20 13:25 UTC, SylteA commented on api/versions/__init__.py
> +from . import v1  # noqa F401
instead of noqa comment do \_\_all__ = (v1)

2021-06-20 13:25 UTC, SylteA commented on api/versions/v1/__init__.py
> +router = APIRouter(prefix="/v1")
define the router in ./router.py

2021-06-20 13:25 UTC, SylteA commented on launch.py
>      )
^^^

2021-06-20 13:25 UTC, SylteA commented on launch.py
>      )
configs should probably be unique to each version of the API

2021-06-20 13:48 UTC, mohamed040406 commented on launch.py
>      )
how is updating how the config works related to fastapi migration? :mhm:

2021-06-20 20:42 UTC, SylteA commented on launch.py
>      )
> how is updating how the config works related to fastapi migration? :mhm:

Each version could be built differently meaning we could be using new / different environment values.
To not run into issues I'd have a different config file for each version 🤷

2021-06-29 09:55 UTC, takos22 requested changes
Nothing big, just a few code improvements that would be great

2021-06-29 09:55 UTC, takos22 commented on README.md
> +- [FastAPI](https://fastapi.tiangolo.com/) - Backend module
Maybe change this to framework instead of module

2021-06-29 09:55 UTC, takos22 commented on api/config.py
> +                    line.strip().split("=") for line in f.readlines() if line.strip()
You should add `line.split("#")[0]` instead of `line` to ignore comments made with #

2021-06-29 09:55 UTC, takos22 commented on api/config.py
> +        if not os.environ.get(key, None):
Change to ``os.environ.setdefault(key, val)``

2021-06-29 09:55 UTC, takos22 commented on api/config.py
> +            if not (val := os.environ.get(k, None)):
You can remove the `None` because `dict.get` default is `None`

2021-06-29 09:55 UTC, takos22 commented on api/config.py
> +    for k, v in __annotations__.copy().items():
Change variable names to like `config, annotation`

2021-06-29 09:55 UTC, takos22 commented on launch.py
> +    host: str, port: str, debug: bool, initdb: bool, verbose: bool, reload: bool
`port: int`

2021-06-29 09:55 UTC, takos22 commented on launch.py
> +        "api.app:app", reload=reload, host=host, port=port, debug=debug
You can change the app to `"api:app"`

2021-06-29 10:17 UTC, SylteA commented on api/config.py
> +                    line.strip().split("=") for line in f.readlines() if line.strip()
Remove the ability to provide a local env file entirely.

If users want to use a different file they can do so in docker-compose api config.

2021-06-29 10:17 UTC, SylteA commented on api/config.py
> +            if not (val := os.environ.get(k, None)):
explicit > implicit

2021-06-29 10:18 UTC, SylteA commented on launch.py
> +    host: str, port: str, debug: bool, initdb: bool, verbose: bool, reload: bool
better to use str 🤷‍♀️
it works anyways

2021-06-29 10:20 UTC, SylteA commented on launch.py
> +        "api.app:app", reload=reload, host=host, port=port, debug=debug
Actually no, not in all cases.
I ran into an issue where I had to explicitly use `api.app:app` instead of `api:app`.
Had something to do with the models.

2021-06-29 10:29 UTC, takos22 commented on api/config.py
> +            if not (val := os.environ.get(k, None)):
If you don't know dict.get default it's not my fault

2021-06-29 10:29 UTC, takos22 commented on launch.py
> +    host: str, port: str, debug: bool, initdb: bool, verbose: bool, reload: bool
The click command gives port=5000 so why would the type hint be str

2021-06-30 17:12 UTC, takos22 approved these changes
Looks good to me

2021-06-30 19:04 UTC, takos22 requested changes

2021-06-30 19:04 UTC, takos22 commented on api/config.py
> +def test_db_uri() -> typing.Optional[str]:
why not test_postgres_uri?

2021-06-30 20:46 UTC, merged

2021-06-30 20:46 UTC, mohamed040406 commented
t.tag party