Migrate discord OAuth to fastapi
Tech-With-Tim/API pull request #50
Opened 2021-07-04 11:49 UTC by mohamed040406

## Summary

Migrate discord OAuth from quart to fastapi

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [x] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [x] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-04 20:50 UTC, takos22 requested changes
Change validation to pydantic and change some things.

2021-07-04 20:50 UTC, takos22 commented on api/models/user.py
> +    @property
This shouldn't be a property because of the arguments

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +from fastapi.params import Param
Replace this with Query, and I think you can import Query directly from fastapi

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +    request: Request, callback: str = Param(None)
Set callback type hint to pydantic.HttpUrl, and you can just do `= None`

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +    if isinstance(callback, list):
You can remove this check

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +    if not is_valid_url(callback):
You can also remove this because pydantic.HttpUrl already validates the URL

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +        request: Request, code: str = Param(...), callback: str = Param(None)
You can remove the `= Param(...)`, and you can change the callback like in `/discord/redirect`

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/models.py
> +    callback: str
Change this to pydantic.HttpUrl

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +        return await post_discord_oauth_callback(code, callback)
This works?

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +    if not is_valid_url(data.callback):
You can remove this check

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +        if 200 < status_code >= 300:
You need an or `status_code < 200 or status_code >= 300`

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/router.py
> +from .auth.routes import router as auth_router
Import the router in `auth/__init__.py` then replace this with `from . import auth`

2021-07-04 20:50 UTC, takos22 commented on api/versions/v1/routers/router.py
> +router.include_router(auth_router)
Change this to `auth.router`

2021-07-04 20:50 UTC, takos22 commented on config.py
> +    return bool(os.environ.get("DEBUG", False))
Why bool, the only way debug will be False is if the env var isn't set, maybe change to `bool(int(...))` so if `DEBUG=0`, the app doesn't run in debug

2021-07-04 20:50 UTC, takos22 commented on tests/test_auth.py
> +    assert res.json() == {
With my changes in the router, change this to just check that the response status code is 422

2021-07-04 20:59 UTC, mohamed040406 commented on api/versions/v1/routers/auth/routes.py
> +        return await post_discord_oauth_callback(code, callback)
yeah i tried it <:mhm:687726663676592145>

2021-07-07 13:23 UTC, mohamed040406 commented on api/versions/v1/routers/auth/routes.py
> +        if 200 < status_code >= 300:
bonk

2021-07-07 15:46 UTC, takos22 reviewed
Some doc changes are needed but otherwise lgtm

2021-07-07 15:46 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +        400: {
You don't need to document this as it will be automatically documented by FastAPI

2021-07-07 15:46 UTC, takos22 commented on api/versions/v1/routers/auth/routes.py
> +        Callback endpoint for finished discord authorization flow.
Add that this is only in debug

2021-07-07 15:47 UTC, takos22 commented
And fix the checks

2021-07-07 19:58 UTC, takos22 approved these changes
Looks good to me

2021-07-10 03:24 UTC, SylteA requested changes

2021-07-10 03:24 UTC, SylteA commented on api/app.py
> +config.set_debug(app.debug)
Can we remove this?

2021-07-10 03:24 UTC, SylteA commented on api/versions/v1/routers/auth/helpers.py
> +    async with aiohttp.ClientSession() as session:
Create and use a global ClientSession

2021-07-10 03:24 UTC, SylteA commented on api/versions/v1/routers/auth/helpers.py
> +    async with aiohttp.ClientSession() as session:
Create and use a global ClientSession

2021-07-10 03:24 UTC, SylteA commented on docker-compose.yml
>      links:
links is deprecated, only use depends_on

2021-07-10 03:24 UTC, SylteA commented on launch.py
> -@click.option("-r", "--reload", default=False, is_flag=True)
Could make it a `resetdb` command, I've found it useful in testing from time to time.

2021-07-10 03:24 UTC, SylteA commented on tests/conftest.py
> +    await client.aclose()
Please use this:
```py
@pytest.fixture(scope="session")
async def app(event_loop) -> AsyncClient:
    """Creates a test client"""
    from api.app import app

    async with AsyncClient(app=app, base_url="http://localhost:8000") as client:
        await app.router.startup()
        yield client
        await app.router.shutdown()
        ```

2021-07-10 03:24 UTC, SylteA commented on tests/test_auth.py
> +@pytest.mark.asyncio
Maybe parameterize this to test multiple values and things like wrong schema?

2021-07-10 03:24 UTC, SylteA commented on tests/test_auth.py
> +    res = await app.get("/v1/auth/discord/redirect")
Should probably disallow redirects and test the Location header.
This way we don't make requests to discord when testing

2021-07-10 03:24 UTC, SylteA commented on tests/test_auth.py
> +        callback="http://127.0.0.1/v1/auth/discord/callback",
no port?
running api on localhost port 80?

2021-07-10 03:24 UTC, SylteA commented on tests/test_auth.py
> +        json={"code": "okand", "callback": "https://twt.gg"},
use the same json as in next test

2021-07-19 13:32 UTC, takos22 commented on launch.py
> -@click.option("-r", "--reload", default=False, is_flag=True)
This can be added in another pr

2021-07-19 13:41 UTC, takos22 commented on api/app.py
> +config.set_debug(app.debug)
Yeah we could

2021-07-23 11:10 UTC, takos22 commented
@mohamed040406 are you planning to do the changes or should someone else do them?

2021-07-23 17:26 UTC, SylteA commented
> @ mohamed040406 are you planning to do the changes or should someone else do them?

technically anyone can do them 👀

2021-08-01 17:32 UTC, SylteA approved these changes
lgtm

2021-08-02 14:23 UTC, takos22 approved these changes
lgtm except for import orders

2021-08-02 14:23 UTC, takos22 commented on api/app.py
>  import logging
Ordering isn't logical at all, ordering by length doesn't make sense to me. Order by first party, third party and local packages and in each of them put `import`s then `from ... import`s and each of these categories order alphabetically or just use `isort`.

2021-08-02 23:01 UTC, merged