Roles
Tech-With-Tim/API pull request #52
Opened 2021-08-29 12:01 UTC by mohamed040406

2021-09-05 16:03 UTC, SylteA requested changes
Documentation needs to be improved (Documenting every response code, updating default response codes, desciptions / summaries for each endpoint)
Any endpoints returning 204 need `""` as content, otherwise they will return `null`

2021-09-05 16:03 UTC, SylteA commented on api/app.py
> +    redoc_url="/api/redoc",
I don't think we need redoc, openAPI is good enough

2021-09-05 16:03 UTC, SylteA commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
Don't need to provide this

2021-09-05 16:03 UTC, SylteA commented on api/dependencies.py
> +async def access_token(request: Request) -> Optional[dict]:
I think it'd be better if we convert this into a `authorization` dependency with the same style as `has_permissions`.

```py
async def authorization(app_only: bool = False):
    async def inner(request: Request):
```

2021-09-05 16:03 UTC, SylteA commented on api/dependencies.py
> +                SELECT position, permissions FROM roles WHERE id IN (SELECT * FROM user_roles);
Format this query better

```sql
WITH userroles AS (
    SELECT ur.role_id
      FROM userroles ur
     WHERE ur.user_id = $1
 )
SELECT r.position
       r.permissions
  FROM roles r
 WHERE r.id IN (
    SELECT role_id
      FROM userroles
)
```

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    return [dict(record) for record in records]
I don't think we need to paginate this endpoint, It's not like we'll have alot of roles anyways.
Also won't this break? I don't think you can do `LIMIT None OFFSET None` which is what this will do without query parameters

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Use dependency instead of checking permissions in endpoint

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    """
```sql
SELECT *,
       r.id::TEXT
  FROM roles r
```

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        WHERE r.id = $1;
```sql
SELECT *,
       id::TEXT,
       COALESCE(
           (
               SELECT json_agg(ur.user_id::TEXT)
                 FROM userroles ur
                WHERE ur.role_id = r.id
           ), '[]'
       ) members
  FROM roles r
 WHERE r.id = $1
 ```

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    try:
newline before `try:`

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(404, "Role Not Found")
Check if role exists after checking permissions

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Check permissions with dependency

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        record = await Role.pool.fetchrow("SELECT * FROM roles WHERE name = $1", name)
This can be checked with `try:except:` on the update query, gives us one less query to execute

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        await Role.pool.execute(query)
These queries could be executed at the same time (in the same call)

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    return utils.JSONResponse(status_code=204)
Maybe we should return the updated role?

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Same comments on fetching role and checking permissions as on previous endpoint

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Same comments on fetching role and checking permissions as on previous endpoint

2021-09-05 16:03 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Same comments on fetching role and checking permissions as on previous endpoint

2021-09-05 16:03 UTC, SylteA commented on tests/conftest.py
> +    )
These will exist between each test, to fix this you can change the fixture scope to function

2021-09-05 16:03 UTC, SylteA commented on utils/permissions.py
> +from typing import Union, List
Add docstrings to the functions

2021-09-05 16:16 UTC, mohamed040406 commented on api/app.py
> +    redoc_url="/api/redoc",
why not tho?

2021-09-05 16:16 UTC, mohamed040406 commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
why?

2021-09-05 16:17 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +    return [dict(record) for record in records]
i tested it, and there are tests

2021-09-05 16:18 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
the dependency doesn't check for role order, does it?

2021-09-05 16:19 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
> the dependency doesn't check for role order, does it?

2021-09-05 16:20 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        record = await Role.pool.fetchrow("SELECT * FROM roles WHERE name = $1", name)
if the user adds a position to the body the position will get updated, while the name won't

2021-09-05 16:21 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +    return utils.JSONResponse(status_code=204)
do we need to?

2021-09-05 16:21 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
> the dependency doesn't check for role order, does it?

2021-09-05 16:21 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
> the dependency doesn't check for role order, does it?

2021-09-05 16:22 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
don't repeat reviews...

2021-09-05 16:22 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
don't repeat reviews...

2021-09-05 16:22 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
> the dependency doesn't check for role order, does it?

2021-09-05 16:22 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
don't repeat reviews...

2021-09-05 16:26 UTC, mohamed040406 commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
we won't be using subdomain so having docs directly on frontend will not make sense

2021-09-05 16:57 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        await Role.pool.execute(query)
no it doesn't work... <:mhm:687726663676592145>

2021-09-05 17:04 UTC, SylteA commented on api/app.py
> +    redoc_url="/api/redoc",
Why would we need 2 sets of documentation

2021-09-05 17:04 UTC, SylteA commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
> we won't be using subdomain so having docs directly on frontend will not make sense

no you have it on `/api/docs`
We don't need the `openapi_url` it's set by default

2021-09-05 17:06 UTC, mohamed040406 commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
`openapi_url`'s default is `/openapi.json`

2021-09-05 17:06 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
Dependency doesn't check it no, but are returning the role permissions and positions so you can use that in the code

2021-09-05 17:06 UTC, mohamed040406 commented on api/app.py
> +    redoc_url="/api/redoc",
i like redoc

2021-09-05 17:08 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +        raise HTTPException(403, "Missing Permissions")
> it returns the role permissions and positions so you can use that in the code

it returns `True/False` if the user has the permission or not

2021-09-05 18:43 UTC, SylteA requested changes

2021-09-05 18:43 UTC, SylteA commented on api/dependencies.py
> +        raise ValueError("can't set both app_only and user_only to True")
`"app_only and user_only are mutually exclusive"`

Sounds better \:)

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    """
remember to update this

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    """
Update formatting like in image, soz

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +            SELECT position, permissions FROM roles WHERE id IN (SELECT * FROM user_roles);
Remember to update this :3

2021-09-05 18:43 UTC, SylteA commented on api/app.py
> +    redoc_url="/api/redoc",
weirdo

2021-09-05 18:43 UTC, SylteA commented on api/app.py
> +    openapi_url="/api/docs/openapi.json",
Ah ok

2021-09-05 18:43 UTC, SylteA commented on api/dependencies.py
> +        return utils.has_permissions(user_permissions, permissions)
Let's do something like 
```py
if not utils.has_permissions(user_permissions, permissions):
    raise HTTPExceiption(403, detail="Missing permissions")

return records
```

If we do this maybe we should fetch more information?
Just fetch the entire roles?

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +                          WHERE ur.role_id = r.id
Fix indents

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +@router.get("", tags=["roles"], response_model=List[RoleResponse], status_code=200)
Status code is 200 by default

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        422: {"description": "Invalid body"},
I think 422 is documented by default?
Correct me if I'm wrong

2021-09-05 18:43 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +        422: {"description": "Invalid body"},
Order by status code instead of length

2021-09-05 18:43 UTC, SylteA commented on utils/permissions.py
> +from typing import Union, List
"this role" ?

2021-09-06 06:35 UTC, SylteA requested changes

2021-09-06 06:35 UTC, SylteA commented on api/dependencies.py
> +        except (jwt.PyJWTError, jwt.InvalidSignatureError):
`jwt.InvalidSignatureError` is subclassed from `jwt.PyJWTError`

2021-09-06 06:35 UTC, SylteA commented on api/dependencies.py
> +        return data
Should return the User object

2021-09-06 06:35 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +    status_code=200,
Status code is 200 by default

2021-09-06 06:35 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +                          FROM userroles ur
Fix formatting

2021-09-06 06:35 UTC, SylteA commented on api/versions/v1/routers/roles/routes.py
> +
Just adding a comment here stating what this will do helps a lot.
```py
# Check if the user has administrator permission or all the permissions provided in the role
```

I don't think we should check all the permissions though, just the permissions that are higher than `ManageRoles`.

2021-09-06 11:09 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +
permissions that are "higher"?

2021-09-06 11:09 UTC, mohamed040406 commented on api/versions/v1/routers/roles/routes.py
> +                          FROM userroles ur
do it yourself

2021-09-06 19:43 UTC, merged