Add challenge language endpoints
Tech-With-Tim/API pull request #60
Opened 2021-09-13 21:34 UTC by takos22

## Summary

Add challenge language endpoints, resolves #59.

## Checklist

- [x] If endpoints were changed then they have been documented and tested.
    - [x] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-10-01 10:56 UTC, mohamed040406 requested changes

2021-10-01 10:56 UTC, mohamed040406 commented on api/services/piston.py
> +    base_url: str = "https://emkc.org/api/v2/piston/"
Use env

2021-10-01 10:56 UTC, mohamed040406 commented on api/services/piston.py
> +        self._session: ClientSession = ClientSession(raise_for_status=True)
We have a global session, why not use it

2021-10-01 10:56 UTC, mohamed040406 commented on api/versions/v1/routers/challenges/languages/routes.py
> +    if name := data.get("name", None):
We can try except the update query instead

2021-10-01 10:59 UTC, SylteA commented on api/services/piston.py
> +        self._session: ClientSession = ClientSession(raise_for_status=True)
You should also not create a ClientSession in a non-asyncronous context

2021-10-01 11:36 UTC, SylteA requested changes

2021-10-01 11:36 UTC, SylteA commented on Pipfile
> +aiohttp = "~=3.7"
Why are you doing this?

2021-10-01 11:36 UTC, SylteA commented on api/services/piston.py
> +        self.runtime = data.get("runtime")
If we're not implementing any methods this can just stay as json or use a namedtuple

2021-10-01 11:36 UTC, SylteA commented on api/services/piston.py
> +__all__ = ("client", "init", "close", "PistonClient", "Runtime")
All other services define `__all__` at the end of the file

2021-10-01 11:36 UTC, SylteA commented on api/services/piston.py
> +        return runtimes_dict.get(language, [])
Should we maybe implement these methods on a module level? (No class)
This implementation requires us to do:
```py
from api.services.piston import client
# Just having a client variable results in bad readability
await client.get_runtimes()

## OR

from api.services import piston
# Importing the piston module means you have to reference 
# the client object inside it before accessing any methods
await piston.client.get_runtimes()
```

Meanwhile implementing them on a module level would mean you just do:
```py
from api.services import piston

await piston.get_runtimes()
```

2021-10-01 11:36 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/helpers.py
> +        raise HTTPException(404, "Piston language version not found")
No return value?

2021-10-01 11:36 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +    tags=["challenge languages"],
I see now that we're using this tags kwarg, but we should do it on the router to avoid this repeating code.
I also see that we've done the same thing on all other endpoints, so I will create an issue and PR to update tags later.

2021-10-01 11:36 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +        ORDER BY name
We should align this by the first space.

```sql
SELECT *,
       l.id::TEXT
  FROM challengelanguages l
 ORDER BY name
 ```
 I've been trying to keep the SQL formatting similar for all PRs but I'm not sure if we want to do it as everyone seems to make the same mistake, or maybe my formatting is just not normal.

2021-10-01 11:36 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +    _=has_permissions([ManageWeeklyChallengeLanguages()]),
If you don't use the dependency anywhere you can include it in the routing decorator.

ex:
```py
@router.post(
  "",
  dependencies=[
    has_permissions([ManageWeeklyChallengeLanguages])
  ]
)
```
I hope I remember the correct kwarg :sweat_smile:

2021-10-01 11:36 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +        SELECT * FROM challenges WHERE $1 = ANY(language_ids)
Instead of `= ANY(...)` can we use the `IN` operator for readability? They are practically the same.

2021-10-01 11:36 UTC, SylteA commented on tests/test_challenges.py
> +    await piston_service.close()
Should we collect all fixtures in `conftest.py` or potentially even create a `fixtures.py` ?

2021-10-01 11:36 UTC, SylteA commented on tests/test_challenges.py
> +async def complete_piston_data(piston: piston_service.PistonClient, data: dict):
Please provide a docstring here so we don't have to read through the code to understand the functionality

2021-10-01 11:38 UTC, SylteA reviewed
Should we also consider changing the filestructure from:
```
api/versions/v1/routers/challenges/languages/routes.py
api/versions/v1/routers/challenges/routes.py
```
To something more descriptive like:

```
api/versions/v1/routers/weekly/challenges/routes.py
api/versions/v1/routers/weekly/languages/routes.py
```

Just a suggestion.

2021-10-01 16:38 UTC, takos22 commented on Pipfile
> +aiohttp = "~=3.7"
It bumps the version to 4.0 otherwise, which fails the tests

2021-10-01 16:40 UTC, takos22 commented on api/versions/v1/routers/challenges/languages/helpers.py
> +        raise HTTPException(404, "Piston language version not found")
It returns nothing when it's good, raises a 404 error otherwise

2021-10-01 16:41 UTC, takos22 commented on api/versions/v1/routers/challenges/languages/routes.py
> +    tags=["challenge languages"],
Tags allow separation of endpoints in the `/docs`

2021-10-01 16:43 UTC, takos22 commented on api/versions/v1/routers/challenges/languages/routes.py
> +        ORDER BY name
The capital letters are already readable enough imo, also your formatting would mean that if you add a line in the query where the 1st space is further, you'd have to reformat everything manually

2021-10-01 16:44 UTC, takos22 commented on tests/test_challenges.py
> +    await piston_service.close()
I added them here because they're only for this test file

2021-10-01 16:48 UTC, takos22 commented on api/services/piston.py
> +__all__ = ("client", "init", "close", "PistonClient", "Runtime")
`__all__` definitions should be just under the import statements, for an overview of what's public in the file without having to read through it. Also, most modules define them at the top

2021-10-01 16:48 UTC, takos22 commented on api/services/piston.py
> +        self.runtime = data.get("runtime")
Now that I did it, I'll leave it like that

2021-10-01 16:51 UTC, takos22 commented on api/versions/v1/routers/challenges/languages/routes.py
> +    if name := data.get("name", None):
It was done like this in the roles endpoints

2021-10-01 17:58 UTC, mohamed040406 commented on api/versions/v1/routers/challenges/languages/routes.py
> +    if name := data.get("name", None):
Ye because we have a separate query for position and updating the position without updating name(conflict) isnogood

2021-10-01 19:22 UTC, SylteA commented on Pipfile
> +aiohttp = "~=3.7"
The older aiohttp version we use the more vulnerabilities we leave open, we already have dependabot alerts.
Is there no other way to solve this?

2021-10-01 19:24 UTC, SylteA commented on api/services/piston.py
> +__all__ = ("client", "init", "close", "PistonClient", "Runtime")
Then either change every single `__all__` reference to fit this or change these ones☺️

2021-10-01 19:25 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +        ORDER BY name
In what case would that ever happen, and you can easily select multiple lines with your average editor

2021-10-02 10:29 UTC, takos22 commented on Pipfile
> +aiohttp = "~=3.7"
The 4.0 is still in beta and they will keep updating 3.x for security fixes

2021-10-08 19:07 UTC, mohamed040406 requested changes

2021-10-08 19:07 UTC, mohamed040406 commented on tests/test_challenges.py
> +        + DeleteWeeklyChallenge().value,
use `|`

2021-10-08 19:07 UTC, mohamed040406 commented on api/versions/v1/routers/challenges/languages/routes.py
> +            raise HTTPException(409, "Language with that name already exists")
👀

2021-10-08 20:01 UTC, takos22 commented on api/versions/v1/routers/challenges/languages/routes.py
> +        SELECT * FROM challenges WHERE $1 = ANY(language_ids)
Using `IN` doesn't work actually, you would need to change `$1 = ANY(language_ids)` into `$1 IN (SELECT unnest(language_ids))` which doesn't improve readability.

2021-10-09 10:00 UTC, SylteA commented on api/versions/v1/routers/challenges/languages/routes.py
> +        SELECT * FROM challenges WHERE $1 = ANY(language_ids)
Oh alright, TIL

2021-10-09 21:17 UTC, SylteA requested changes

2021-10-09 21:17 UTC, SylteA commented on config.py
> +        log.warning('Optional environment variable "PISTON_URL" is missing')
As you've added a default, value will never be `None`

2021-10-09 21:19 UTC, SylteA approved these changes

2021-10-09 21:23 UTC, SylteA approved these changes

2021-10-19 16:01 UTC, mohamed040406 approved these changes

2021-10-19 16:01 UTC, merged